name: Bandit Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run bandit
      uses: tj-actions/bandit@v5.1
# 1. heckout the code using actions/checkout
# 2. Run bandit using tj-actions bandit
