name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vulnerable-image .

      - name: Run web app container
        run: |
          docker run -d -p 8080:80 --name test-app vulnerable-image
          sleep 10  # Give app time to boot

