name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: |
        docker build -t Security-automation-lab:latest .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'Security-automation-lab:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
        

# 1. Checkout the code
# 2. Instal docker buildx  docker/setup-buildx-action@v3
# 3. Build the docker image
# 4. Scan with trivy the built image
